### ISSUE TITLE
建议更改难度选择功能

### ISSUE THREAD

**Issue by azhuquq** [eiko-g/maimaidx-roll#1]
作者您好 这个项目解决了我打maimai不知道选什么歌的问题
提个建议
可以在不选择难度的情况下抽选曲目吗
或者增加一个难度区间的功能
希望您能考虑

**Comment by eiko-g** [comment]
🉑，无条件随机抽歌是计划内的功能了。

难度区间的话感觉一般用得比较少，可以考虑一下。
