### ISSUE TITLE
Money Money封面错误

### ISSUE THREAD

**Issue by Louiswu2011** [eiko-g/maimaidx-roll#2]
json中Money Money的图片文件名与CYBER Sparks重复

> {
      "分类": "toho",
      "曲名": "CYBER Sparks",
      "BPM": "192",
      "等级": {
        "B": "5",
        "A": "7",
        "E": "10",
        "M": "10+",
        "R": "12+"
      },
      "类型": "标准",
      "封面": **"1524e99570ce2fff2ed70ff658fa1554"**
    }

>{
      "分类": "toho",
      "曲名": "Money Money",
      "BPM": "145",
      "等级": {
        "B": "4",
        "A": "6",
        "E": "9",
        "M": "12",
        "R": "-"
      },
      "类型": "标准",
      "封面": **"1524e99570ce2fff2ed70ff658fa1554"**
    }

**Comment by Louiswu2011** [comment]
顺带一提 LOVE EAST 的封面和 Money Money 的也重复了，，，

**Comment by Louiswu2011** [comment]
兄啊 找了一下发现 LOVE EAST 的封面好像没有找到

**Comment by eiko-g** [comment]
这几天找时间修
