### ISSUE TITLE
歌曲封面使用华立的是否可以？

### ISSUE THREAD

**Issue by qa003qa003** [eiko-g/maimaidx-roll#5]
https://maimai.wahlap.com/maimai-mobile/img/Music/c3e9be8d22de76f7.png
https://maimai.wahlap.com/maimai-mobile/img/Music/c023c6efc6447818.png
https://maimai.wahlap.com/maimai-mobile/img/Music/2d53766d4a3020c0.png

感觉会快点，就是要抓出出来

**Comment by eiko-g** [comment]
不可以，不考虑盗链。
